lab_1/urls.py
from django.urls import re_path, path
from .views import index, contact, message
#url for app
app_name='lab_1'
urlpatterns = [
    re_path(r'^$', index, name='index'),
    path('message/', message, name='message'),
    path('contact/', contact, name='contact'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'', include('lab_1.urls')),
    # re_path(r'^lab-2/', include('lab_2.urls')),
    # re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# Create your models here.

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
# Create your views here.
def index(request):
    response = {}
    return render(request, 'index_lab1.html', response)

def contact(request):
    response = {}
    return render(request, 'contact.html', response)

def message(request):
    response = {}
    return render(request, 'message.html', response)

lab_1/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>contact</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Insanul Fahmi</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</head>
<body>

	{%include "header.html"%}
	
	<div class="container container_contact">
        <div class="row row_contact">
            
        	<div class="col-lg-12">
        		<form action="" enctype="multipart/form-data" id="form_id"> 
            		
            		<div class="form-group">
                 		<h5><label for="inputName">Name</label></h5>

                	<input type="text" name="career[name]" class="form-control" tabindex="1" placeholder="Enter your name" pattern="[a-zA-Z. ]{1,50}" required>
            		</div>
            
            		
            		<div class="form-group">
                		<h5><label for="inputEmail">Email</label></h5>

                	<input type="email" name="career[email]" class="form-control" tabindex="2" placeholder="Enter your email address" required>
            		</div>
            
            		
            		<div class="form-group">
                 		<h5><label for="inputMobile">Mobile</label></h5>

                	<input type="tel" name="career[mobile]" class="form-control" tabindex="3" placeholder="Enter your mobile number" pattern="[0-9]{10}" maxlength="10" required>
            		</div>
            
            		
            		<div class="form-group">
                 	<h5><label for="inputMessage">Message</label></h5>

                	<textarea name="career[message]" class="form-control" tabindex="4" placeholder="Write your details" required></textarea>
            
            		<div>
	            		<button type="button" name="submit" class="btn btn-primary btn-block" tabindex="5">
	            			<a href="{% url 'lab_1:contact' %}" class="btn-text">submit</a>
	            		</button>
	            	</div>
        		</form>
    		</div>

        </div>
    </div>
</body>
</html>

lab_1/templates/header.html
{% load static %}
<div>
        <nav class="navbar fixed-top navbar-expand-md navbar-dark">
            <a class="navbar-brand" href="#">
                <img style="height: 50px;" src="{% static 'images/sanwa.png' %}">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:index' %}#">HOME</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:index' %}#about">ABOUT</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:index' %}#experience">EXPERIENCE</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:index' %}#business">BUSINESS</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'lab_1:contact' %}">CONTACT</a>
                    </li>

                </ul>
            </div>
        </nav>

        <div class="jumbotron text-center" id = "jumbotron_top"></div>
    </div>

lab_1/templates/index_lab1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Insanul Fahmi</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>

<body>

    {%include "header.html"%}

<!-- ***********************************-container_1-************************************* -->

    <div class="container container_1">
        <div class="row row_1">
            <div class="col-md-5 px-4 pt-4"> 
                <ul>
                    <li>
                        <h1 class="judul nama">Insanul Fahmi</h1>
                    </li>

                    <li style="margin-top: -10px;">
                        <h1 class="judul aktivitas">Young Entrepreneur</h1>
                    </li>
                </ul>
            </div>
        
            <div class="col-md-7 image-insan-1">
              <img class="images image_1" src="{% static 'images/insan_1.png' %}" alt="My image" style="margin-top: 1px;">

            </div>
        </div>
    </div>

<!-- ***********************************-container_2-************************************* -->

    <div id="about" class="container container_2">
        <div class="row row_2">
            <div class="col-md-5 image-insan-2">
                <img class="images image_2" src="{% static 'images/about.jpeg' %}" alt="image">
            </div>

            <div class="col-md-7 isi-about">

                <h1 class="judul about">ABOUT</h1>
                <p class="paragraph_1">Halo! Nama saya Insanul Fahmi, saat ini saya sedang berkuliah di Universitas Indonesia, Fakultas Ilmu Komputer. Selain ngoding, hobi saya yang sedang saya tekuni saat ini yaitu berdagang. Menurut saya berdagang itu seru karena selain mendapatkan uang, saya juga menjadi punya banyak relasi dan selalu berinteraksi dengan sekitar. Soal tujuan berdagang saya mempunyai misi yang sederhana, yaitu membantu umat.</p>

            </div>

        </div>
    </div>

<!-- ***********************************-container_3-************************************* -->

    <div id="experience" class="container container_3">
        <div class="row row_3">

            <div class="col-md-4">
                
            </div>

            <div class="col-md-4">
                <div class="rectangle rectangle_1">
                    <h1 class="judul">EXPERIENCE</h1>
                </div>
                
            </div>

            <div class="col-md-4">
                
            </div>

<!-- ************************************************************************ -->

            <div class="col-md-3">
                
            </div>

<!-- ***********************************-box TK-************************************* -->

            <div class="col-md-6" style="text-align: center;">
                
                <div class="line_vertical line-v-1"></div>
                <div class="circle">
                    <h2 class="sekolah">TK</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">Yayasan Jayawijaya, Tembaga Pura</h6>
                    <h6 class="box-title grey">2003 - 2004</h6>
                    <p class="box-title white">Pada saat TK saya mulai tertarik belajar berhitung. Karena sangking sukanya berhitung orangtua saya memasukan saya ke les sempoa agar kemampuan berhitung saya semakin bertambah.</p>
                </div>

<!-- ***********************************-box SD-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="circle">
                    <h2 class="sekolah">SD</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">SD IT Asy-Syammil, Bontang</h6>
                    <h6 class="box-title grey">2004 - 2010</h6>
                    <p class="box-title white">Pada saat SD kelas 2 saya jualan makanan seperti permen dan coklat, 1 hari saya bisa profit 50 ribu. Naik kelas 4 saya jualan mainan dengan profit per hari 150 ribu. Saya tau teman teman saya waktu itu anak-anak, dan itu saya jadikan peluang.</p>
                </div>

<!-- ***********************************-box SMP-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="circle">
                    <h2 class="sekolah">SMP</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">SMP IT Al-Fityan, Medan</h6>
                    <h6 class="box-title grey">2011 - 2013</h6>
                    <p class="box-title white">Pada saat SMP saya sangat maniak sekali bermain game. Zaman SMP ini saya lebih banyak transaksi di game online (Trading Item) yang bisa ditukar dalam bentuk uang Cash Rupiah.</p>
                </div>
                
<!-- ***********************************-box SMA-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="circle">
                    <h2 class="sekolah">SMA</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">SMA N 3 MEDAN, Medan</h6>
                    <h6 class="box-title grey">2014 - 2017</h6>
                    <p class="box-title white">Berhenti bermain game, pada saat SMA saya mencoba berbagai macam usaha. Salah satunya jualan air mineral dan makanan di sekolah. Satu bulan pendapatan kami (tim) bisa sampai belasan juta.</p>
                </div>

<!-- ***********************************-box KULIAH-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="rectangle rectangle_2">
                    <h2 style="margin-top: -9px">KULIAH</h2>
                </div>

                <div class="box box_4">
                    <h6 class="box-title orange">Univeristy of Indonesia</h6>
                    <p class="box-title white">Berhenti bermimpi dan bangun untuk mewujudkan mimpi tersebut. Selama 16 tahun jiwa entrepreneurku telah kuasah, maka sudah bukan saatnya bermain main lagi. Sebelum kami bangun bersama sama bisnis ini (tim). Aku mulai semuanya dengan banyak kegagalan, namun aku tahu itu hanya hanya proses menuju kesuksesan. “Tugas manusia hanya berikhtiar, hasilnya hanya Allah yang menentukan.” - Sanwa Store</p>
                </div>

<!-- ************************************************************************ -->

            </div>

            <div class="col-md-3">
                
            </div>
        </div>
    </div>


<!-- ***********************************-container_4-************************************* -->
        
    <div id="business" class="container-fluid container_4">
        <div class="row">
            <div class="col-md-12">
                <div class="gambar text-center">
                    <img class="images image_3" src="{% static 'images/kurma2.jpeg' %}" alt="image">
                </div>
            </div>

<!-- ********************************************************************* -->
    
            <div class="col-md-5 text-center">
                <div>
                    <h1 class="judul_business">BUSINESS</h1>
                </div>

                <div>
                    <img class="images image_4" src="{% static 'images/sanwa.png' %}" alt="image">
                </div>

                <div class="orange_box_left">
                <p class="orange_title_left">Berawal dari membuka toko baju, Sanwa Store yang saat ini sudah berdiri sejak bulan Februari 2019 lebih memilih untuk fokus memenuhi kebutuhan masyarakat  berupa barang - barang yang diimport dari luar Indonesia. Khususnya saat ini untuk kebutuhan kesehatan masyarakat Indonesia. Setiap penjualanan, Sanwa Store menyalurkan donasi sebesar 5% profit untuk Masyarakat Indonesia yang membutuhkan. Belanja di Sanwa Store sama dengan berdonasi 5%.</p>
                </div>
            
            </div>

            <div class="col-md-2 text-center">
                <ul>
                    <li style="text-shadow: 1px 1px 3px; margin-top: 70px;">
                        <h6>PRODUK</h6>
                    </li>
                        
                    <li style="color: white; text-shadow: 1px 1px 5px #000000; margin-top: 20px;">
                        <h6>Kurma Ajwah</h6>
                    </li>

                    <li style="color: white; text-shadow: 1px 1px 5px #000000;">
                        <h6>Saffron Kashmir</h6>
                    </li>
                </ul>
            </div>

            <div class="col-md-5 text-center">
                
                <div style="margin-top: 65px;">
                    <ul>
                        <li><img class="images image_5" src="{% static 'images/gmail.png' %}" alt="image"></li>
                        <li><img class="images image_6" src="{% static 'images/instagram.png' %}" alt="image"></li>
                        <li><img class="images image_7" src="{% static 'images/whatsapp.png' %}" alt="image"></li>
                    </ul>
                </div>

                <div>
                    <ul class="list_sanwastore text-center">
                        <li style="padding-bottom: 27px;">sanwa.toko@gmail.com</li>
                        <li style="padding-bottom: 27px;">@sanwa.store</li>
                        <li>+6287896438982</li>
                    </ul>
                </div>
            
            </div>

    
            <div class="background_orange_1"></div>

        </div>
    </div>


<!-- ***********************************-container_5-************************************* -->
    <div class="container container_5 text-center">
        
        <div class="row">
            <div class="col-md-12">
                
                <div>
                    <h1 class="judul_contact text-center">CONTACT</h1>
                </div>

                <div>
                <p class="title_contact text-center">Hubungi saya jika ingin mengetahui bisnis yang saya dirikan!</p>
                </div>

                <div class="button_contact">
                    <button type="button" class="btn btn-secondary">
                        <a href="{% url 'lab_1:contact' %}" class="btn-text">hubungi saya</a>
                    </button>
                </div>

                <div>
                    <h6 style="font-size: 13px; margin-top: 50px;">© Insanul Fahmi</h6>
                </div>

            </div>

        </div>

        <div class="container background_orange_2"></div>
    </div>

</body>
</html>

lab_1/templates/message.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>message</title>

	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Insanul Fahmi</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
</head>
<body>
	{%include "header.html"%}

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}